### PR TITLE
Story/character limit

### LINKED ISSUE #58: Other field character limit still shows when unchecked
**Bug description**
When the user fills in too many characters in the other field, then unchecks it and submits the form, the "You're over the character limit" still appears.

**To Reproduce**
1. Click on a checkbox other than "Other"
2. Click on other and fill the textbox until it's over the limit
3. Uncheck other
4. Click submit

**Expected behavior**
The error message about the Other character limit should not appear if the user has unchecked other.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by ksiegel1923**

### CODE REVIEW

File: feedback-module/src/lib/hooks/useInputs.js [hunk 1]
```diff
@@ -60,8 +61,14 @@ export default function useInputs(firstCheckRef) {
         invalidPhone(question.answer, question.required)
       ) {
         (validated = false), (question.error = true);
+      } else if (
+        question.type === "textarea" &&
+        question.answer.length > TEXTAREA_MAX_CHAR
+      ) {
+        (validated = false), (question.charError = true);
```
Comment (michellexliu) [inline feedback-module/src/lib/hooks/useInputs.js]: Is there a reason we need this to be charError instead of just error? Also, I noticed that there are a lot of repeated checks going on between this `inputsValidated` function and the `inputError` function in `TextboxList` (for example, we check `question.type` here and `input.type` in TextboxList.js.) I feel like it would make things simpler if instead of `question.error` being a boolean, we set `question.error` to be the actual error message key or undefined if there is none. Then, instead of doing all these checks again in the `inputError` function and separating out `error` and `charError`, we could just do a simple
```
if (inputQuestions && inputQuestions[index] && inputQuestions[index].error) {
const key = inputQuestions[index].error;
return (
      <ErrorAlert
        key={key}
        errorText={t(`errorMessages.${key}`)}
        id={id}
        className="margin-bottom-2"
      />
    );
}

Comment (michellexliu) [reply feedback-module/src/lib/hooks/useInputs.js]: Also, probably not a big deal, but the `validated` variable seems a little unnecessary to me and seems kind of redundant to have to set it in each if/else if body. I think it might be cleaner if we just return
```
return !inputQuestions.some(question => question.error);
```
at the very end

**Review by michellexliu — APPROVED** [review]

**Review by michellexliu — APPROVED** [review]

File: feedback-module/src/components/Module.js [hunk 2]
```diff
@@ -84,20 +90,40 @@ function Module({ pagetitle, endpoint, dir }) {
...
+        screen.checkboxes &&
+        screen.checkboxes.required &&
+        !checkboxValidated(checkedFields)
+      ) {
+        setCheckboxError(true);
+        firstCheckRef.current && firstCheckRef.current.focus();
+      } else if (!otherFieldValidated()) {
+        setOtherTooLong(true);
+      }
+      if (screen.textInputs && !inputsValidated()) {
```
Comment (michellexliu) [inline feedback-module/src/components/Module.js]: Is there a reason this is an `if` instead of an `else if`? If there is a missing checkbox and an improper input at the same time, the focus should go to the checkbox since it comes before, but right now it goes to the input instead.

Comment (ksiegel1923) [reply feedback-module/src/components/Module.js]: If this is an else if then it will only show the checkbox error even if there are two errors

Comment (michellexliu) [reply feedback-module/src/components/Module.js]: I see— should we add an extra check for the checkboxError then, so that we're not accidentally focusing on the input instead of the checkbox? So `if (screen.textInputs && !inputsValidated() && !checkboxError)`
